# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build Qt OHOS

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [ windows-2022, ubuntu-22.04, macos-14 ]
        arch: [ arm64-v8a, armeabi-v7a, x86-64 ]
        api: [ 15 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: build
        run: |
          echo '{
            "config": {
              "working_dir": "${pwd}/work",
              "perl": "${pwd}/work/perl/bin",
              "mingw": "${pwd}/work/mingw/bin",
              "ohos_sdk": "${pwd}/work/ohos-sdk/${ohos_version}",
              "ohos_version":  "${{ matrix.api }}",
              "build_type": "release",
              "build_ohos_abi": "${{ matrix.arch }}",
              "build_qt_tag": "v5.15.12-lts-lgpl",
              "build_ohqt_tag": "dev",
              "clone_depth": 1,
              "jobs": 4,
              "verbose": false
            }
          }' > configure.json.user
          python ./build-qt-ohos.py --init
          python ./build-qt-ohos.py --exe_stage all --with_pack
          

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output-${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.api }}
          path: |
            work/output/*.zip
            work/output/*.tar.gz
