# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build Qt OHOS

on:
  workflow_dispatch:
    inputs:
      qt_version:
        description: '选择Qt版本'
        required: true
        default: 5.15.12
        type: choice
        options: [5.15.12, 5.15.17]

      ohos_version:
        description: '选择OpenHarmony版本'
        required: true
        default: '17'
        type: choice
        options: ['15', '16', '17', '18', '19', '20']

      build_type:
        description: '选择构建类型'
        required: true
        default: release
        type: choice
        options: [debug, release]


permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [ windows-2022, ubuntu-22.04, macos-14 ]
        arch: [ arm64-v8a, armeabi-v7a, x86-64 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: build
        run: |
          echo '{
            "config": {
              "working_dir": "${pwd}/work",
              "perl": "${pwd}/work/perl/bin",
              "mingw": "${pwd}/work/mingw/bin",
              "ohos_sdk": "${pwd}/work/ohos-sdk/${ohos_version}",
              "ohos_version": ${{ inputs.ohos_version }},
              "build_type": "${{ inputs.build_type }}",
              "build_ohos_abi": "${{ matrix.arch }}",
              "build_qt_tag": "v${{ inputs.qt_version }}-lts-lgpl",
              "build_ohqt_tag": "dev",
              "clone_depth": 1,
              "jobs": 4,
              "verbose": false
            }
          }' > configure.json.user
          python ./build-qt-ohos.py --init
          python ./build-qt-ohos.py --exe_stage all --with_pack
          

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-output-qt${{ inputs.qt_version }}-${{ matrix.arch }}-${{ inputs.ohos_version }}-${{ inputs.build_type }}
          path: |
            work/output/*.zip
            work/output/*.tar.gz
